services:
    _defaults:
        autowire: true
        autoconfigure: true

    Arthem\ObjectReferenceBundle\Mapper\ObjectMapper: ~
    Arthem\ObjectReferenceBundle\Doctrine\ObjectReferenceListener: ~
